name: Production

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  production:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
      - run: pnpm dlx vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
      - run: pnpm dlx vercel build --token ${{ secrets.VERCEL_TOKEN }}
      - id: deploy
        run: |
          URL=$(pnpm dlx vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }})
          echo "production_url=$URL" >> $GITHUB_OUTPUT
      - name: Deployment summary
        run: echo "Production URL: ${{ steps.deploy.outputs.production_url }}" >> $GITHUB_STEP_SUMMARY
